openapi: 3.0.0
info:
  title: Cat Database
  description: Cat Database RESTful API Documentation
  version: 0.0.1
servers:
  - url: http://localhost:8000
    description: local
securitySchemes:
  - name: Authorization
    in: header
    description: ID of the requested TaxFiling
    required: true
    schema:
      type: object
      properties:
        message:
          type: string
          example: Unauthorized
      responses:
        401:
          description: Bad Request
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: FAIL
                  message:
                    type: string
                    example: Email / Password  salah
paths:
  /register:
    description: Register new Member
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: farah@mail.com
                password:
                  type: string
                  example: farah123
      responses:
        201:
          description: New Member Created
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: CREATED
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      email:
                        type: string
                        example: farah@mail.com
                      password:
                        type: string
                        example: farah123
                      updatedAt: 
                        type: string
                        format: date-time
                      createdAt: 
                        type: string
                        format: date-time
  /login:
    post:
      tags:
        - Authentication
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: farah@mail.com
                password:
                  type: string
                  example: farah123
      responses:
        200:
          description: Login Success
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      email:
                        type: string
                        example: farah@mail.com
                      token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IiB1ZGluQG1haWwuY29tIiwicGFzc3dvcmQiOiIgYXNkMTIzIiwiaWF0IjoxNjUyNDYzMzIzfQ.pPRA_IBwHs2PI4yMSyX_PareM0LTNLk43KBKH5Ehg5c
        400:
          description: Bad Request
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: FAIL
                  message:
                    type: string
                    example: Email / Password  salah
      

  /create:
    post:
      tags:
        - CRUD
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: zorro
                age:
                  type: integer
                  example: 7
                breed:
                  type: string
                  example: persia
      responses:
        201:
          description: New Cat Data Created
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: CREATED
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: zorro
                      age:
                        type: integer
                        example: 7
                      breed:
                        type: string
                        example: persia
                      updatedAt: 
                        type: string
                        format: date-time
                      createdAt: 
                        type: string
                        format: date-time
  /findAll:
    get:
      tags:
        - CRUD
      responses:
        200:
          description: List of all cats data
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  data:
                    type: array
                    items:
                      oneOf:
                        - type: object
                          properties:
                            id:
                              type: integer
                              example: 2
                            name:
                              type: string
                              example: zorro
                            age:
                              type: integer
                              example: 7
                            breed:
                              type: string
                              example: persia
                            updatedAt: 
                              type: string
                              format: date-time
                            createdAt: 
                              type: string
                              format: date-time
                        - type: object
                          properties:
                            id:
                              type: integer
                              example: 3
                            name:
                              type: string
                              example: muti
                            age:
                              type: integer
                              example: 1
                            breed:
                              type: string
                              example: british short hair
                            updatedAt: 
                              type: string
                              format: date-time
                            createdAt: 
                              type: string
                              format: date-time
  /update/{id}:
    post:
      tags:
        - CRUD
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: zorro
                age:
                  type: integer
                  example: 7
                breed:
                  type: string
                  example: persia
      responses: 
        200:
          description: Data Updated
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
  /delete/{id}:
    get:
      tags:
        - CRUD
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Data deleted
          content:
            application/x-www-form-urlencoded:
              schema:
                type: integer
                example: 1
  /findbyid/{id}:
    get:
      tags:
        - CRUD
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Find Data By Id
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: zorro
                      age:
                        type: integer
                        example: 7
                      breed:
                        type: string
                        example: persia
                      updatedAt: 
                        type: string
                        format: date-time
                      createdAt: 
                        type: string
                        format: date-time
                      
  
      
  
                    
                  
        
        
                      